### ISSUE TITLE
GDB step over becomes step into

### ISSUE THREAD

**Issue by hcindyl** [renode/renode#233]
Use Renode + gdb for a RISCV32 target. If I use "next" to step over functions, it actually steps into the function, and I would need to explicitly step out of the function with "finish". It seems to be the same behavior as "step"

**Comment by mateusz-holenko** [comment]
Hi @hcindyl, thanks for reporting the issue!

We found a problem in a generation of registers list that was reported to GDB. This lead to a wrong interpretation of exchanged 
packets and caused general registers (x1 - x31) to have wrong values according to GDB.
This could be a root cause of problems with stepping over functions and backtracking.

Could you check if eb0f1449086ade58f43ba23c986bf45972d79185 solves the problem for you?

**Comment by hcindyl** [comment]
Thanks Mateusz for the fix. Yes it seems to address the GDB problems we encounter, including step over, register value query, and backtrace.
