### ISSUE TITLE
Renode + TensorflowLite + NUCLEO-L476RG (NUCLEO 64 ARM M4)

### ISSUE THREAD

**Issue by RAnastacioo** [renode/renode#239]
hello I'm interested in using the node with tensorflow lite and simulating on the NUCLEO-L476RG board (NUCLEO 64 ARM M4).
Is there any example I can base myself on to implement my academic project?

greeting

**Comment by PiotrZierhoffer** [comment]
This is quite a complex question.

First you need to model the platform in Renode. This requires you to have models of peripherals and the platform description file.

Since we do have a plenty of STM32 platforms, you probably can just reuse the models that we have. Scan through our current supported platforms (https://github.com/renode/renode/tree/master/platforms) and try to find something similar. For example, we have an [STM32L151](https://github.com/renode/renode/blob/master/platforms/cpus/stm32l151.repl)

Then you need to create your own REPL file: basing on the existing one, adjust the addresses of peripherals, memory sizes and interrupt connections. You can look up the [documentation](https://renode.readthedocs.io/en/latest/advanced/platform_description_format.html), but I recommend you just read and adjust one of the sample REPL files we have.

Then, of course, you need TFLM ported to your platform. As far as I know this Nucleo is not there yet.

With the binary, you need a trivial resc script that will load your platform and the application you want to run.

Renode is used by TensorFlow Lite Micro for CI purposes, you can find some resc and repl files in their repo as well: https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/testing

**Comment by mgielda** [comment]
Since the question is answered and there is no further feedback from the issue creator, closing this. Can be reopened if needed.
