### ISSUE TITLE
GDB: Line length limit is short

### ISSUE THREAD

**Issue by xobs** [renode/renode#54]
It appears as though the line length for GDB commands is rather short -- about 48 characters -- resulting in commands getting cut off:

```
(gdb) mon sysbus LoadELF @../kernel/target/riscv32i-unknown-none-elf/debug/xous-kernel
There was an error executing command 'sysbus LoadELF @../kernel/target/riscv32i-unkno'
Error while loading ELF: Could not find file '../kernel/target/riscv32i-unkno'..
        Could not find file '../kernel/target/riscv32i-unkno'.
(gdb)
```

**Comment by mateusz-holenko** [comment]
This is related to a little innocent “feature” we introduced in order to nicely log the content of GDB packets (https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Main/Utilities/GDB/PacketData.cs#L106-L109).

Since `DataAsString` is used not only for logging, but also when parsing all GDB commands - the “feature” breaks handling long packets.

This should be fairly easy to fix - use limited version in logs, but the full one everywhere else.

**Comment by mateusz-holenko** [comment]
@xobs - the newest master (https://github.com/renode/renode/commit/3a27c5bc23f5309c94a6f7ea14e70b917c591301) should solve the problem with the truncated long GDB commands.

**Comment by truhlikfredy** [comment]
@mateusz-holenko thanks for the fix

**Comment by xobs** [comment]
I verify that it is now fixed.  Would you like me to close this issue?

**Comment by mateusz-holenko** [comment]
That's great it works. I'm closing this one.
