### ISSUE TITLE
Passing SGI to underlying CPU instance

### ISSUE THREAD

**Issue by ya-mouse** [renode/renode#673]
I'm trying to bring-up second core of STM32MP1 when booting Linux:

```
NOTICE:  CPU: STM32MP153CAA Rev.Z
NOTICE:  Model: EVB
NOTICE:  Board: MB90a0 Var11.12 Rev.@-00
...
VERBOSE: FIP header looks OK.
INFO:    Loading image id=2 at address 0xc0500000
INFO:    Image id=2 loaded: 0xc0500000 - 0xc0515920
INFO:    BL2: Loading image id 16
VERBOSE: FIP header looks OK.
INFO:    Loading image id=16 at address 0x2ffc0000
INFO:    Image id=16 loaded: 0x2ffc0000 - 0x2ffc423b
INFO:    BL2: Loading image id 5
VERBOSE: FIP header looks OK.
INFO:    Loading image id=5 at address 0xc0100000
INFO:    Image id=5 loaded: 0xc0100000 - 0xc01bbf80
NOTICE:  BL2: Booting BL32
INFO:    Entry point address = 0x2ffc5000
INFO:    SPSR = 0x1d3
...
INFO:    SP_MIN: Initializing runtime services
INFO:    SP_MIN: Preparing exit to normal world

U-Boot 2021.10-stm32mp-r2-uboot-g26dd8a9898 (May 31 2024 - 14:53:44 +0000)
CPU: STM32MP153CAA Rev.Z
Model: EVB
DRAM:  512 MiB
VERBOSE: SCMI clock 13 enable
...
Uncompressing Linux... done, booting the kernel.
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.15.67-yocto-standard (oe-user@oe-host) (arm-linux-gnueabi-gcc (GCC) 11.3.0, GNU ld (GNU Binutils) 2.38.20220708) #1 SMP PREEMPT Thu May 23 06:43:32 UTC 2024
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.007699] CPU: Testing write buffer coherency: ok
...
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.2
...
[    0.008399] /cpus/cpu@0 missing clock-frequency property
[    0.008499] /cpus/cpu@1 missing clock-frequency property
[    0.008599] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.011599] Setting up static identity map for 0xc0100000 - 0xc0100060
[    0.012099] rcu: Hierarchical SRCU implementation.
[    0.014599] smp: Bringing up secondary CPUs ...
```

The installed SVC handler by FIP generates an interrupt and I cannot find how to properly pass it down to emulated CPU:

```
14:07:17.4570 [NOISY] MP1/gic: The cpu0.0.0.0 requests an SGI with id 0.
14:07:17.4571 [NOISY] MP1/gic: Trying to request interrupt for target cpu1.0.0.0, interrupt group type (GICD_IGROUPRn) Group0, request group (NSATT) Group0, access in secure state.
14:07:17.4572 [NOISY] MP1/gic: Setting Software Generated Interrupt #0 signal for cpu1.0.0.0
14:07:17.4572 [NOISY] MP1/gic: cpu0.0.0.0 writes to 0xF00 (SoftwareGeneratedInterruptControl) register of Distributor, value 0x20000.
14:07:17.4586 [NOISY] MP1/gic: The cpu0.0.0.0 requests an SGI with id 8.
14:07:17.4586 [NOISY] MP1/gic: Trying to request interrupt for target cpu1.0.0.0, interrupt group type (GICD_IGROUPRn) Group0, request group (NSATT) Group0, access in secure state.
14:07:17.4586 [NOISY] MP1/gic: Setting Software Generated Interrupt #8 signal for cpu1.0.0.0
14:07:17.4587 [NOISY] MP1/gic: cpu0.0.0.0 writes to 0xF00 (SoftwareGeneratedInterruptControl) register of Distributor, value 0x20008.
```

Not sure how `gic` should be properly configured. Part of repl:
```
cpu0: CPU.ARMv7A @ sysbus
    cpuType: "cortex-a7"
    genericInterruptController: gic
    cpuId: 0

cpu1: CPU.ARMv7A @ sysbus
    cpuType: "cortex-a7"
    genericInterruptController: gic
    cpuId: 1

scu: Miscellaneous.ArmSnoopControlUnit @ sysbus 0xae000000

pmu0: Miscellaneous.ArmPerformanceMonitoringUnit @ cpu0
    -> gic@5

cpuTimer: Timers.ARM_GenericTimer @ cpu0
    frequency: 24000000
    EL1PhysicalTimerIRQ -> gic@26
    EL1VirtualTimerIRQ -> gic@25
    NonSecureEL2PhysicalTimerIRQ -> gic@24
    NonSecureEL2VirtualTimerIRQ -> gic@27
    EL3PhysicalTimerIRQ -> gic@28

gic: IRQControllers.ARM_GenericInterruptController @ {
        sysbus new Bus.BusMultiRegistration { address: 0xa0021000; size: 0x1000; region: "distributor" };
        sysbus new Bus.BusMultiRegistration { address: 0xa0022000; size: 0x2000; region: "cpuInterface" }
    }
//    [0, 8] -> cpu1@[0, 1]
    architectureVersion: IRQControllers.ARM_GenericInterruptControllerVersion.GICv2
    supportsTwoSecurityStates: false
/*
    CPUInterfaceProductIdentifier: 0x390
    CPUInterfaceRevision: 0x2
    CPUInterfaceImplementer: 0x43B
*/

exti: IRQControllers.STM32H7_EXTI @ sysbus <0x5000d000, +0x400>

privateTimer0: Timers.ARM_PrivateTimer @ {
        sysbus new Bus.BusPointRegistration { address: 0x40001000; cpu: cpu0 }
    }
    -> gic#0@29
    frequency: 667000000

privateTimer1: Timers.ARM_PrivateTimer @ {
        sysbus new Bus.BusPointRegistration { address: 0x40001000; cpu: cpu1 }
    }
    -> gic#1@29
    frequency: 667000000
```

PS. I did some extra changes to arm emulation lib to support missed features / instructions / operation mode (i.e. monitor) as well as `cortex-a7` config that is based on `cortex-a9`. 

PPS. Second CPU is running in a simple loop waiting for interrupt:

```
(MP1) cpu0 PC
0x2ffdfb20

(MP1) cpu1 PC
0x4c
```

```
.global _start
.align 4

.section .vector_table, "ax"
vector_table:
    ldr pc, =_start
    b . //  =undefined_handler
    b . // ldr pc, =svc_handler
    b . // ldr pc, =prefetch_abort_handler
    b . // ldr pc, =data_abort_handler
    b . // ldr pc, =unused_handler
    ldr pc, =handle_interrupt
    b . // ldr pc, =fiq_handler

// Constants
.equ TAMP_BASE, 0x5C00A000
.equ TAMP_BKP_REGISTER_BASE, TAMP_BASE + 0x100
.equ BOOT_API_CORE1_BRANCH_ADDRESS_TAMP_BCK_REG_IDX, 5
.equ BOOT_API_CORE1_MAGIC_NUMBER_TAMP_BCK_REG_IDX, 4
.equ BOOT_API_A7_CORE1_MAGIC_NUMBER, 0xCA7FACE1

.section .text
_start:
    // Identify CPU core number
    mrc p15, 0, r0, c0, c0, 5  // Read MPIDR
    and r0, r0, #0xFF
    cmp r0, #0
    beq primary_core

secondary_core:
    // Setup interrupt vector table for secondary core
    ldr r0, =vector_table
    mcr p15, 0, r0, c12, c0, 0  // Write VBAR

secondary_wait_for_interrupt:
    wfi
    b secondary_wait_for_interrupt

handle_interrupt:
    // Check if it's interrupt #8
    mrc p15, 0, r0, c5, c0, 1  // Read IFSR
    ldr r1, =0x3FF
    and r0, r0, r1
    cmp r0, #8
    bne secondary_wait_for_interrupt

    // Read TAMP backup register for magic number
    ldr r1, =TAMP_BKP_REGISTER_BASE
    add r1, r1, #(BOOT_API_CORE1_MAGIC_NUMBER_TAMP_BCK_REG_IDX << 2)
    ldr r0, [r1]

    // Check magic number
    ldr r2, =BOOT_API_A7_CORE1_MAGIC_NUMBER
    cmp r0, r2
    bne secondary_wait_for_interrupt

    // Read entry point from TAMP backup register
    ldr r1, =TAMP_BKP_REGISTER_BASE
    add r1, r1, #(BOOT_API_CORE1_BRANCH_ADDRESS_TAMP_BCK_REG_IDX << 2)
    ldr r0, [r1]

    // Branch to entry point
    bx r0

primary_core:
    // Primary core jumps to firmware
    bx lr

.end
```

**Comment by MateuszKarlic** [comment]
Hi @ya-mouse ,

At first glance, it looks like you might have IRQ lines disconnected between your GIC and CPUs. You could connect them like so:
```
gic: IRQControllers.ARM_GenericInterruptController @ {
        sysbus new Bus.BusMultiRegistration { address: 0xa0021000; size: 0x1000; region: "distributor" };
        sysbus new Bus.BusMultiRegistration { address: 0xa0022000; size: 0x2000; region: "cpuInterface" }
    }
    [0-3] -> cpu0@[0-3]
    [4-7] -> cpu1@[0-3]
    architectureVersion: IRQControllers.ARM_GenericInterruptControllerVersion.GICv2
    supportsTwoSecurityStates: false
```

Generally the pattern is as follows, if you take a look at `ARM_GenericInterruptController` model:
```c#
    // GIC should use GPIO#0 of an ARM CPU to signal IRQ and GPIO#1 to signal FIQ
    // An ARM CPU should be connected to a GIC following the convention `[<N*4>-<N*4+3>] -> cpuN@[0-3]`";
    public enum InterruptSignalType
    {
        IRQ  = 0,
        FIQ  = 1,
        vIRQ = 2,
        vFIQ = 3,
    }
```
    
You can take a look at: https://github.com/renode/renode/blob/master/platforms/cpus/cortex-a9_smp.repl or https://github.com/renode/renode/blob/master/platforms/cpus/cortex-r8_smp.repl or even: https://github.com/renode/renode/blob/master/platforms/cpus/zynqmp.repl to see how we configure GIC for SMP platforms. Notice, the correct version of the GIC, but the connection scheme of interrupts is always the same. `zynqmp.repl` should also use GICv2, so it might be the closest to your use case.

Then, your application should be able to raise SGIs, and they should be processed and forwarded by GIC.

**Comment by MateuszKarlic** [comment]
I think we misunderstood each other a bit. The convention is that we pass only 4 IRQ lines to each CPU, where each line signifies, in this specific order - IRQ, FIQ, virtual IRQ, virtual FIQ.

The SGI is a type of IRQ, so when you trigger SGI, an interrupt "signal" will be generated on the IRQ line - so on the first one (`0 -> cpu0@0`) you connect to your CPU. So there is no need to connect 8 lines to the CPU, since any interrupts you will generate will likely be either passed as IRQ or FIQ. We need to distinguish here between an interrupt "number" (which can be anything more or less than 4) and interrupt "line" (which are only 4), that we use to signal that an interrupt has occurred. There is no way to assign that an `SGI #8` will be passed through line `#8`, that's not how the GIC is expected to work. You can inspect [zynqmp_linux.resc](https://github.com/renode/renode/blob/master/scripts/single-node/zynqmp_linux.resc) demo and see how Linux handles passing IRQs between cores.

Have you tried exactly the configuration I suggested before, with the first 4 interrupts connected to CPU0, and next 4 to CPU1? The reason I asked you to try this is because you might need to generate a SGI to target a specific CPU, so the connection order, and `cpuId` parameters will matter greatly here (https://developer.arm.com/documentation/ihi0048/b/Interrupt-Handling-and-Prioritization/General-handling-of-interrupts/Interrupt-controls-in-the-GIC?lang=en).

From the logs it seems that the SGI is generated. The reason why it's not passed might be because you connected the CPUs in an unexpected way, and the GIC tries to activate an unconnected/incorrect IRQ line. Note, that you can simulate IRQ line state change on the target CPU, by using `cpu1 OnGPIO 0 true` to activate the IRQ signal, or `cpu1 OnGPIO 0 false` to deactivate the signal and check if your application reacts correctly to the interrupt being activated.

While it's possible that our implementation of GIC is lacking something, we have verified it with a range of software (including Linux), so I'd like first to be sure that there is no accidental misconfiguration going on here :).

**Comment by MateuszKarlic** [comment]
I see, right, this CPU has only two lines. So please try with:
```
gic:
    [0,1] -> cpu0@[0,1]
    [4,5] -> cpu1@[0,1]
```
I base this on an SMP platform using ARMv7A which is here (though it uses `cortex-a9` and `GICv1`): https://github.com/renode/renode/blob/master/platforms/cpus/cortex-a9_smp.repl

As for GIC "CPU interface", I think that this CPU should access the memory-mapped region, instead of using system registers (you would also see a warning in the logs, if the CPU tried to access an unimplemented system register).

**Comment by MateuszKarlic** [comment]
Glad to hear that everything worked out :) Yes, the bug with the log crashing Renode will have to be taken of.

Closing this issue then

**Comment by spalani7** [comment]
@ya-mouse - I've been trying to have the renode setup for stm32mp157c-ev1 board. I havent had any success in booting uboot. Would you share your setup files and necessary uboot and linux images to provide me a reference?
